version: '3.4'

services:
  documan.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "5101:80"    
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
